# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: True

# Try to make build faster with mamba. See:
# https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba
# https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
build:
  os: "ubuntu-20.04"
  tools:
    python: "miniconda3-4.7"
#     python: "mambaforge-4.10"

conda:
  environment: docs/env.yml

python:
  install:
    - method: pip
      path: .
