name: graphblas
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python=3.10
    - python-graphblas
    - matplotlib
    - networkx
    - pandas
    - scipy
    - drawsvg
    - cairosvg
