name: Test and Build

on:
  # Run this workflow every time a PR is opened or a new commit is pushed to the PR
  pull_request:
  # Run this workflow every time a PR is merged to main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup conda env
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda install -q conda-build
          conda create -n grblas -c conda-forge python=3.8 pytest-runner coverage black>=20.8 flake8
      - name: Lint
        run: |
          flake8 grblas *.py
          black grblas *.py --check --diff
